// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdDspWEI_2zXLcrhxieu81GAzVUnUxbvg',
    appId: '1:204720492146:web:5fb0bc3bcd7b5b7d2b7ceb',
    messagingSenderId: '204720492146',
    projectId: 'kuldeepsharma-work-gmail-com',
    authDomain: 'kuldeepsharma-work--com.firebaseapp.com',
    storageBucket: 'kuldeepsharma-work-gmail-com.firebasestorage.app',
  );
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzpdJpX8m9abCJhWDl7gPE4hCQzIkGTE',
    appId: '1:204720492146:android:9324b8b9550b03232b7ceb',
    messagingSenderId: '204720492146',
    projectId: 'kuldeepsharma-work-gmail-com',
    storageBucket: 'kuldeepsharma-work-gmail-com.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdDspWEI_2zXLcrhxieu81GAzVUnUxbvg',
    appId: '1:204720492146:web:f09e2406b8761c632b7ceb',
    messagingSenderId: '204720492146',
    projectId: 'kuldeepsharma-work-gmail-com',
    authDomain: 'kuldeepsharma-work--com.firebaseapp.com',
    storageBucket: 'kuldeepsharma-work-gmail-com.firebasestorage.app',
  );

}